.test-schema:
  stage: test
  image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-docker:19.03.12-1
  services:
    - name: $CI_REGISTRY/mattermost/ci/images/docker-dind:19.03.12-1
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_CONTENT_TRUST: 0
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ""
  before_script:
    - |
      curl -sSLo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-linux-amd64
      chmod +x kind
      mv kind /usr/local/bin/

    - |
      curl -sSLO https://storage.googleapis.com/kubernetes-release/release/v1.19.4/bin/linux/amd64/kubectl ; \
      chmod +x ./kubectl ; \
      mv ./kubectl /usr/local/bin/kubectl

    - |
      curl -sSLO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.8.7/kustomize_v3.8.7_linux_amd64.tar.gz ; \
      tar -zxvf kustomize_v3.8.7_linux_amd64.tar.gz ; \
      mv ./kustomize /usr/local/bin/kustomize

    - |
      kind create cluster --config=./.gitlab-ci/kind-config.yaml --name ci-mm-${CI_PIPELINE_ID} --wait 3m
      sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' "$HOME/.kube/config"

    - kustomize build build | kubectl apply -f -

    - |
      kubectl wait --for=condition=ready pod -l com.mattermost/component=dejavu
      kubectl wait --for=condition=ready pod -l com.mattermost/component=elasticsearch
      kubectl wait --for=condition=ready pod -l com.mattermost/component=inbucket
      kubectl wait --for=condition=ready pod -l com.mattermost/component=keycloack
      kubectl wait --for=condition=ready pod -l com.mattermost/component=minio
      kubectl wait --for=condition=ready pod -l com.mattermost/component=mysql
      kubectl wait --for=condition=ready pod -l com.mattermost/component=openldap
      kubectl wait --for=condition=ready pod -l com.mattermost/component=postgres

    # - |
    #   cat ../tests/test-data.ldif | docker-compose --no-ansi exec -T openldap bash -c 'ldapadd -x -D "cn=admin,dc=mm,dc=test,dc=com" -w mostest'
  after_script:
    - kind delete cluster --name ci-mm-${CI_PIPELINE_ID}
