.test-schema:
  stage: test
  image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-docker:19.03.12-1
  services:
    - name: $CI_REGISTRY/mattermost/ci/images/docker-dind:19.03.12-1
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_CONTENT_TRUST: 0
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ""
    KUBECONFIG: /kubeconfig
  before_script:
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - |
      cat <<EOF >>build/kustomization.yaml
      namePrefix: "ci-${CI_PIPELINE_ID}-"
      commonLabels:
        com.mattermost/branch: "${CI_COMMIT_BRANCH}"
        com.mattermost/pipeline: "${CI_PIPELINE_ID}"
      EOF

    - |
      curl -sSLO https://storage.googleapis.com/kubernetes-release/release/v1.19.4/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      mv ./kubectl /usr/local/bin/kubectl

    - |
      curl -sSLO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.8.7/kustomize_v3.8.7_linux_amd64.tar.gz
      tar -zxvf kustomize_v3.8.7_linux_amd64.tar.gz
      mv ./kustomize /usr/local/bin/kustomize

    - kustomize build build/ | kubectl -n mm-ci apply -f -
    - |
      function get_pod_name() {
        if [ -n "$1" ]; then
          kubectl get pod -n mm-ci -l=com.mattermost/component="$1" -l=com.mattermost/pipeline="${CI_PIPELINE_ID}" -o jsonpath='{.items[0].metadata.name}'
        fi
      }

    - kubectl wait -n mm-ci --for=condition=ready pod --all=true --timeout=5m
    - kubectl exec -n mm-ci -t $(get_pod_name "minio") -- sh -c 'mkdir -p /data/mattermost-test'

    # - |
    #   cat ../tests/test-data.ldif | docker-compose --no-ansi exec -T openldap bash -c 'ldapadd -x -D "cn=admin,dc=mm,dc=test,dc=com" -w mostest'
  after_script:
    - kustomize build build/ | kubectl -n mm-ci delete -f -
