name: mattermost-build
on:
  push
jobs:
  check-mocks:
    name: Check mocks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mattermost-server
        uses: actions/checkout@v3
      - name: Generate mocks
        run: make mocks
      - name: Check mocks
        run: if [[ -n $(git status --porcelain) ]]; then echo "Please update the mocks using `make mocks`"; exit 1; fi
  check-go-mod-tidy:
    name: Check go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mattermost-server
        uses: actions/checkout@v3
      - name: Run go mod tidy
        run: make modules-tidy
      - name: Check modules
        run: if [[ -n $(git status --porcelain) ]]; then echo "Please tidy up the Go modules using make modules-tidy"; git diff; exit 1; fi
  check-gen-serialized:
    name: Check serialization methods for hot structs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mattermost-server
        uses: actions/checkout@v3
      - name: Run make-gen-serialized
        run: make gen-serialized
      - name: Check serialized
        run: if [[ -n $(git status --porcelain) ]]; then echo "Please update the serialized files using 'make gen-serialized'"; exit 1; fi
  check-mattermost-vet:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mattermost-server
        uses: actions/checkout@v3
      - name: Checkout focalboard
        run: |
          cd ..
          git clone --depth=1 --no-single-branch https://github.com/mattermost/focalboard.git  
          cd focalboard
          git checkout $GITHUB_HEAD_REF || git checkout $GITHUB_BASE_REF || git checkout rolling-stable
          echo $(git rev-parse HEAD)
          cd ../mattermost-server
          make setup-go-work
      - name: Reset config
        run: make config-reset
      - name: Run plugin-checker
        run: make plugin-checker
      - name: Run mattermost-vet
        run: make vet BUILD_NUMBER='${GITHUB_HEAD_REF}' MM_NO_ENTERPRISE_LINT=true MM_VET_OPENSPEC_PATH='${PWD}/../mattermost-api-reference/v4/html/static/mattermost-openapi-v4.yaml'
  check-migrations:
    name: Check migration files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mattermost-server
        uses: actions/checkout@v3
      - name: Extract migrations files
        run: make migrations-extract
      - name: Check migration files
        run: if [[ -n $(git status --porcelain) ]]; then echo "Please update the migrations using make migrations-extract"; exit 1; fi
  build-api-spec:
    name: Build API specification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mattermost-server
        uses: actions/checkout@v3
      - name: Checkout mattermost-api-reference
        run: |
          cd ..
          git clone --depth=1 --no-single-branch https://github.com/mattermost/mattermost-api-reference.git
          cd mattermost-api-reference
          echo "Trying to checkout the same branch on mattermost-api-reference as mattermost-server"
          git checkout $GITHUB_HEAD_REF || git checkout $GITHUB_BASE_REF || true
          make build
          cd ../mattermost-server

