name: mattermost-govet
on:
  push
permissions:
  contents: read
jobs:
  go-vet:
    name: Mattermost go-vet check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run go-vet
      run: |
        echo "Running go-vet"
        make check-style
